config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:index] do
    patch :like, on: :member
  end

  root to: 'articles#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  def total_likes
    local_likes + remote_likes
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    ImportArticles.call

    @articles = Article.all
  end

  def like
    article = Article.find(params[:id])

    article.increment! :local_likes

    redirect_to articles_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/articles/index.html.slim
h1 Listing articles

table
  thead
    tr
      th Title
      th Description
      th Likes
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = article.description
        td = article.total_likes
        td = link_to 'Like', like_article_path(article), method: :patch

app/views/layouts/application.html.slim
doctype html
html
  head
    title OlioArticles
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield